#!/usr/bin/env bash

# Export the public key of a key pair to a PEM format certificate.
# Usage: ./export_certificate foo.p12
# Output: foo.pem

p12="$(basename $1)"
name="${p12%.*}"
pem="$name.pem"

keytool -exportcert -storetype PKCS12 -rfc -keystore "$1" -file $pem -alias $name
